### ISSUE TITLE
Handle icons and background images for 7xx weather codes

### ISSUE THREAD

**Issue by iamplugged** [Screenly-Labs/weather-app#13]
We don't handle 7xx category weather codes at the moment.

We need to show relevant icons and backgrounds to handle all 7xx cases. 

Grouping: 
Mist, Fog, Haze, Smoke
Sand, Dust
Volcanic Ash,
Squall,
Tornado

<img width="730" alt="image" src="https://user-images.githubusercontent.com/6959733/189341032-5d09b5c6-4ca6-47f9-add5-1871658339a3.png">

**Comment by vpetersson** [comment]
@iamplugged can this be closed out?

**Comment by iamplugged** [comment]
Yes this has been taken care of.
