### ISSUE TITLE
Weather App not showing up in OSE after Skin change

### ISSUE THREAD

**Issue by extremeskillz** [Screenly-Labs/weather-app#49]
I noticed you guys updated the screen weather app skin. For some reason on the screens the weather info does not show up but it does show up if I put the URL in a separate browser for testing. 
I went as far as reconfiguring the weather app to make a new URL and adding it back to screenly and same result of no data showing on the screenly screens but it does in a new browser on my desktop for example. What can be the cause and how should I fix it?

**Comment by vpetersson** [comment]
We've tested it on OSE and it should work fine. Only chance is that if you are running the 'old' production release. If so, you're still using the old generation browser, where it is very plausible that it is broken.

The solution is to upgrade or re-install the latest release as per the updated installation instructions.
